### ISSUE TITLE
Mnist example missing source code

### ISSUE THREAD

**Issue by xyhuang** [mlcommons/mlcube_examples#6]
Cannot find the main function script and the docker file which were in the `/build` dir in the old repo.
Not sure whether it was removed on purpose, but I think it should be included.

**Comment by sergey-serebryakov** [comment]
@xyhuang 
Yeah, it was removed on purpose. Idea was to pull from docker hub not build (Docker runner pulls a docker image if `build/Dockerfile` file does not exist). In PR #7, source code is back.
